config/routes.rb
Openfoodnetwork::Application.routes.draw do
  root :to => 'home#index'

  # Redirects from old URLs avoid server errors and helps search engines
  get "/enterprises", to: redirect("/")
  get "/products", to: redirect("/")
  get "/products/:id", to: redirect("/")
  get "/t/products/:id", to: redirect("/")
  get "/about_us", to: redirect(ContentConfig.footer_about_url)

  get "/login", to: redirect("/#/login")

  get "/discourse/login", to: "discourse_sso#login"
  get "/discourse/sso", to: "discourse_sso#sso"

  get "/map", to: "map#index", as: :map
  get "/sell", to: "home#sell", as: :sell

  get "/register", to: "registration#index", as: :registration
  get "/register/auth", to: "registration#authenticate", as: :registration_auth
  post "/user/registered_email", to: "spree/users#registered_email"

  # Redirects to global website
  get "/connect", to: redirect("https://openfoodnetwork.org/#{ENV['DEFAULT_COUNTRY_CODE'].andand.downcase}/connect/")
  get "/learn", to: redirect("https://openfoodnetwork.org/#{ENV['DEFAULT_COUNTRY_CODE'].andand.downcase}/learn/")

  get "/cart", :to => "spree/orders#edit", :as => :cart
  put "/cart", :to => "spree/orders#update", :as => :update_cart
  put "/cart/empty", :to => 'spree/orders#empty', :as => :empty_cart

  resource :cart, controller: "cart" do
    post :populate
  end

  resource :shop, controller: "shop" do
    get :products
    post :order_cycle
    get :order_cycle
    get :changeable_orders_alert
  end

  resources :producers, only: [:index] do
    collection do
      get :signup
    end
  end

  resources :shops, only: [:index] do
    collection do
      get :signup
    end
  end

  resources :line_items, only: [:destroy] do
    get :bought, on: :collection
  end

  resources :groups, only: [:index, :show] do
    collection do
      get :signup
    end
  end

  namespace :stripe do
    resources :callbacks, only: [:index]
    resources :webhooks, only: [:create]
  end

  get '/checkout', :to => 'checkout#edit' , :as => :checkout
  put '/checkout', :to => 'checkout#update' , :as => :update_checkout
  get '/checkout/paypal_payment/:order_id', to: 'checkout#paypal_payment', as: :paypal_payment

  get 'embedded_shopfront/shopfront_session', to: 'application#shopfront_session'
  post 'embedded_shopfront/enable', to: 'application#enable_embedded_styles'
  post 'embedded_shopfront/disable', to: 'application#disable_embedded_styles'

  resources :enterprises do
    collection do
      post :search
      get :check_permalink
    end

    member do
      get :shop
      get :relatives
    end
  end
  get '/:id/shop', to: 'enterprises#shop', as: 'enterprise_shop'
  get "/enterprises/:permalink", to: redirect("/") # Legacy enterprise URL

  namespace :api do
    resources :enterprises do
      post :update_image, on: :member
      get :managed, on: :collection
      get :accessible, on: :collection

      resource :logo, only: [:destroy]
      resource :promo_image, only: [:destroy]
    end

    resources :order_cycles do
      get :managed, on: :collection
      get :accessible, on: :collection
    end

    resources :orders, only: [:index]

    resource :status do
      get :job_queue
    end

    resources :customers, only: [:index, :update]

    resources :enterprise_fees, only: [:destroy]

    post '/product_images/:product_id', to: 'product_images#update_product_image'
  end

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  # Mount engine routes
  mount Web::Engine, :at => '/'
  mount OrderManagement::Engine, :at => '/'

  # Mount Spree's routes
  mount Spree::Core::Engine, :at => '/'
end

app/models/order_cycle.rb
require 'open_food_network/scope_variant_to_hub'

class OrderCycle < ActiveRecord::Base
  belongs_to :coordinator, :class_name => 'Enterprise'

  has_many :coordinator_fee_refs, class_name: 'CoordinatorFee'
  has_many :coordinator_fees, through: :coordinator_fee_refs, source: :enterprise_fee

  has_many :exchanges, :dependent => :destroy

  has_and_belongs_to_many :schedules, join_table: 'order_cycle_schedules'

  # TODO: DRY the incoming/outgoing clause used in several cases below
  # See Spree::Product definition, scopes variants and variants_including_master
  # This will require these accessors to be renamed
  attr_accessor :incoming_exchanges, :outgoing_exchanges

  validates_presence_of :name, :coordinator_id
  validate :orders_close_at_after_orders_open_at?

  after_save :refresh_products_cache

  preference :product_selection_from_coordinator_inventory_only, :boolean, default: false

  scope :active, lambda { where('order_cycles.orders_open_at <= ? AND order_cycles.orders_close_at >= ?', Time.zone.now, Time.zone.now) }
  scope :active_or_complete, lambda { where('order_cycles.orders_open_at <= ?', Time.zone.now) }
  scope :inactive, lambda { where('order_cycles.orders_open_at > ? OR order_cycles.orders_close_at < ?', Time.zone.now, Time.zone.now) }
  scope :upcoming, lambda { where('order_cycles.orders_open_at > ?', Time.zone.now) }
  scope :not_closed, lambda { where('order_cycles.orders_close_at > ? OR order_cycles.orders_close_at IS NULL', Time.zone.now) }
  scope :closed, lambda { where('order_cycles.orders_close_at < ?', Time.zone.now).order("order_cycles.orders_close_at DESC") }
  scope :undated, where('order_cycles.orders_open_at IS NULL OR orders_close_at IS NULL')
  scope :dated, where('orders_open_at IS NOT NULL AND orders_close_at IS NOT NULL')

  scope :soonest_closing,      lambda { active.order('order_cycles.orders_close_at ASC') }
  # TODO This method returns all the closed orders. So maybe we can replace it with :recently_closed.
  scope :most_recently_closed, lambda { closed.order('order_cycles.orders_close_at DESC') }

  scope :soonest_opening,      lambda { upcoming.order('order_cycles.orders_open_at ASC') }

  scope :by_name, order('name')

  scope :with_distributor, lambda { |distributor|
    joins(:exchanges).merge(Exchange.outgoing).merge(Exchange.to_enterprise(distributor))
  }

  scope :managed_by, lambda { |user|
    if user.has_spree_role?('admin')
      scoped
    else
      where('coordinator_id IN (?)', user.enterprises)
    end
  }

  # Return order cycles that user coordinates, sends to or receives from
  scope :accessible_by, lambda { |user|
    if user.has_spree_role?('admin')
      scoped
    else
      with_exchanging_enterprises_outer.
        where('order_cycles.coordinator_id IN (?) OR enterprises.id IN (?)', user.enterprises, user.enterprises).
        select('DISTINCT order_cycles.*')
    end
  }

  scope :with_exchanging_enterprises_outer, lambda {
    joins('LEFT OUTER JOIN exchanges ON (exchanges.order_cycle_id = order_cycles.id)').
      joins('LEFT OUTER JOIN enterprises ON (enterprises.id = exchanges.sender_id OR enterprises.id = exchanges.receiver_id)')
  }

  scope :involving_managed_distributors_of, lambda { |user|
    enterprises = Enterprise.managed_by(user)

    # Order cycles where I managed an enterprise at either end of an outgoing exchange
    # ie. coordinator or distributor
    joins(:exchanges).merge(Exchange.outgoing).
      where('exchanges.receiver_id IN (?) OR exchanges.sender_id IN (?)', enterprises, enterprises).
      select('DISTINCT order_cycles.*')
  }

  scope :involving_managed_producers_of, lambda { |user|
    enterprises = Enterprise.managed_by(user)

    # Order cycles where I managed an enterprise at either end of an incoming exchange
    # ie. coordinator or producer
    joins(:exchanges).merge(Exchange.incoming).
      where('exchanges.receiver_id IN (?) OR exchanges.sender_id IN (?)', enterprises, enterprises).
      select('DISTINCT order_cycles.*')
  }

  def self.first_opening_for(distributor)
    with_distributor(distributor).soonest_opening.first
  end

  def self.first_closing_for(distributor)
    with_distributor(distributor).soonest_closing.first
  end

  def self.most_recently_closed_for(distributor)
    with_distributor(distributor).most_recently_closed.first
  end

  # Find the earliest closing times for each distributor in an active order cycle, and return
  # them in the format {distributor_id => closing_time, ...}
  def self.earliest_closing_times
    Hash[
      Exchange.
        outgoing.
        joins(:order_cycle).
        merge(OrderCycle.active).
        group('exchanges.receiver_id').
        select('exchanges.receiver_id AS receiver_id, MIN(order_cycles.orders_close_at) AS earliest_close_at').
        map { |ex| [ex.receiver_id, ex.earliest_close_at.to_time] }
    ]
  end

  def clone!
    oc = self.dup
    oc.name = I18n.t("models.order_cycle.cloned_order_cycle_name", order_cycle: oc.name)
    oc.orders_open_at = oc.orders_close_at = nil
    oc.coordinator_fee_ids = self.coordinator_fee_ids
    oc.preferred_product_selection_from_coordinator_inventory_only = self.preferred_product_selection_from_coordinator_inventory_only
    oc.save!
    self.exchanges.each { |e| e.clone!(oc) }
    oc.reload
  end

  def suppliers
    enterprise_ids = self.exchanges.incoming.pluck :sender_id
    Enterprise.where('enterprises.id IN (?)', enterprise_ids)
  end

  def distributors
    enterprise_ids = self.exchanges.outgoing.pluck :receiver_id
    Enterprise.where('enterprises.id IN (?)', enterprise_ids)
  end

  def variants
    Spree::Variant.
      joins(:exchanges).
      merge(Exchange.in_order_cycle(self)).
      not_deleted.
      select('DISTINCT spree_variants.*').
      to_a # http://stackoverflow.com/q/15110166
  end

  def supplied_variants
    self.exchanges.incoming.map(&:variants).flatten.uniq.reject(&:deleted?)
  end

  def distributed_variants
    self.exchanges.outgoing.map(&:variants).flatten.uniq.reject(&:deleted?)
  end

  def variants_distributed_by(distributor)
    return Spree::Variant.where("1=0") unless distributor.present?
    Spree::Variant.
      not_deleted.
      merge(distributor.inventory_variants).
      joins(:exchanges).
      merge(Exchange.in_order_cycle(self)).
      merge(Exchange.outgoing).
      merge(Exchange.to_enterprise(distributor))
  end

  def products_distributed_by(distributor)
    variants_distributed_by(distributor).map(&:product).uniq
  end

  def products
    self.variants.map(&:product).uniq
  end

  def has_distributor?(distributor)
    self.distributors.include? distributor
  end

  def has_variant?(variant)
    self.variants.include? variant
  end

  def dated?
    !undated?
  end

  def undated?
    self.orders_open_at.nil? || self.orders_close_at.nil?
  end

  def upcoming?
    self.orders_open_at && Time.zone.now < self.orders_open_at
  end

  def open?
    self.orders_open_at && self.orders_close_at &&
      Time.zone.now > self.orders_open_at && Time.zone.now < self.orders_close_at
  end

  def closed?
    self.orders_close_at && Time.zone.now > self.orders_close_at
  end

  def exchange_for_distributor(distributor)
    exchanges.outgoing.to_enterprises([distributor]).first
  end

  def exchange_for_supplier(supplier)
    exchanges.incoming.from_enterprises([supplier]).first
  end

  def receival_instructions_for(supplier)
    exchange_for_supplier(supplier).andand.receival_instructions
  end

  def pickup_time_for(distributor)
    exchange_for_distributor(distributor).andand.pickup_time || distributor.next_collection_at
  end

  def pickup_instructions_for(distributor)
    exchange_for_distributor(distributor).andand.pickup_instructions
  end

  def exchanges_carrying(variant, distributor)
    exchanges.supplying_to(distributor).with_variant(variant)
  end

  def exchanges_supplying(order)
    exchanges.supplying_to(order.distributor).with_any_variant(order.variants)
  end

  def coordinated_by?(user)
    coordinator.users.include? user
  end

  def refresh_products_cache
    OpenFoodNetwork::ProductsCache.order_cycle_changed self
  end

  def items_bought_by_user(user, distributor)
    # The Spree::Order.complete scope only checks for completed_at date, does not ensure state is "complete"
    orders = Spree::Order.complete.where(state: "complete", user_id: user, distributor_id: distributor, order_cycle_id: self)
    scoper = OpenFoodNetwork::ScopeVariantToHub.new(distributor)
    items = Spree::LineItem.joins(:order).merge(orders)
    items.each { |li| scoper.scope(li.variant) }
  end

  private

  def orders_close_at_after_orders_open_at?
    return if orders_open_at.blank? || orders_close_at.blank?
    return if orders_close_at > orders_open_at
    errors.add(:orders_close_at, :after_orders_open_at)
  end
end

app/controllers/api/order_cycles_controller.rb
module Api
  class OrderCyclesController < Spree::Api::BaseController
    respond_to :json
    def managed
      authorize! :admin, OrderCycle
      authorize! :read, OrderCycle
      @order_cycles = OrderCycle.ransack(params[:q]).result.managed_by(current_api_user)
      render params[:template] || :bulk_index
    end

    def accessible
      @order_cycles = if params[:as] == "distributor"
        OrderCycle.ransack(params[:q]).result.
          involving_managed_distributors_of(current_api_user).order('updated_at DESC')
      elsif params[:as] == "producer"
        OrderCycle.ransack(params[:q]).result.
          involving_managed_producers_of(current_api_user).order('updated_at DESC')
      else
        OrderCycle.ransack(params[:q]).result.accessible_by(current_api_user)
      end

      render params[:template] || :bulk_index
    end
  end
end

app/helpers/order_cycles_helper.rb
module OrderCyclesHelper
  def current_order_cycle
    @current_order_cycle ||= current_order(false).andand.order_cycle
  end

  def permitted_enterprises_for(order_cycle)
    OpenFoodNetwork::OrderCyclePermissions.new(spree_current_user, order_cycle).visible_enterprises
  end

  def permitted_producer_enterprises_for(order_cycle)
    permitted_enterprises_for(order_cycle).is_primary_producer.by_name
  end

  def permitted_producer_enterprise_options_for(order_cycle)
    validated_enterprise_options permitted_producer_enterprises_for(order_cycle)
  end

  def permitted_coordinating_enterprises_for(order_cycle)
    Enterprise.managed_by(spree_current_user).is_distributor.by_name
  end

  def permitted_coordinating_enterprise_options_for(order_cycle)
    validated_enterprise_options permitted_coordinating_enterprises_for(order_cycle)
  end

  def permitted_hub_enterprises_for(order_cycle)
    permitted_enterprises_for(order_cycle).is_hub.by_name
  end

  def permitted_hub_enterprise_options_for(order_cycle)
    validated_enterprise_options permitted_hub_enterprises_for(order_cycle), shipping_and_payment_methods: true
  end

  def order_cycle_status_class(order_cycle)
    if order_cycle.undated?
      'undated'
    elsif order_cycle.upcoming?
      'upcoming'
    elsif order_cycle.open?
      'open'
    elsif order_cycle.closed?
      'closed'
    end
  end

  def order_cycle_options
    @order_cycles.
      with_distributor(current_distributor).
      map { |oc| [order_cycle_close_to_s(oc.orders_close_at), oc.id] }
  end

  def order_cycle_close_to_s(orders_close_at)
    "%s (%s)" % [orders_close_at.strftime("#{orders_close_at.day.ordinalize} %b"),
                 distance_of_time_in_words_to_now(orders_close_at)]
  end

  def active_order_cycle_for_distributor?(distributor)
    OrderCycle.active.with_distributor(@distributor).present?
  end

  def simple_index
    @simple_index ||= !OpenFoodNetwork::Permissions.new(spree_current_user).can_manage_complex_order_cycles?
  end

  def order_cycles_simple_form
    @order_cycles_simple_form ||= @order_cycle.coordinator.sells == 'own'
  end

  def pickup_time(order_cycle = current_order_cycle)
    order_cycle.exchanges.to_enterprises(current_distributor).outgoing.first.pickup_time
  end

  def can_delete?(order_cycle)
    Spree::Order.where(order_cycle_id: order_cycle).none?
  end

  def viewing_as_coordinator_of?(order_cycle)
    Enterprise.managed_by(spree_current_user).include? order_cycle.coordinator
  end

  private

  def validated_enterprise_options(enterprises, options={})
    enterprises.map do |e|
      disabled_message = nil
      if options[:shipping_and_payment_methods] && (e.shipping_methods.empty? || e.payment_methods.available.empty?)
        if e.shipping_methods.empty? && e.payment_methods.available.empty?
          disabled_message = I18n.t(:no_shipping_or_payment)
        elsif e.shipping_methods.empty?
          disabled_message = I18n.t(:no_shipping)
        elsif e.payment_methods.available.empty?
          disabled_message = I18n.t(:no_payment)
        end
      end

      if disabled_message
        ["#{e.name} (#{disabled_message})", e.id, {disabled: true}]
      else
        [e.name, e.id]
      end
    end
  end
end

app/views/admin/order_cycles/_coordinator_fees.html.haml
%ol.coordinator-fees
  %li{'ng-repeat' => 'enterprise_fee in order_cycle.coordinator_fees'}
    = select_tag 'order_cycle_coordinator_fee_{{ $index }}_id', nil, {'ng-model' => 'enterprise_fee.id', 'ng-options' => 'enterprise_fee.id as enterprise_fee.name for enterprise_fee in enterpriseFeesForEnterprise(order_cycle.coordinator_id)'}
    = link_to t(:remove), '#', {'id' => 'order_cycle_coordinator_fee_{{ $index }}_remove', 'ng-click' => 'removeCoordinatorFee($event, $index)'}

= f.submit t('.add'), 'ng-click' => 'addCoordinatorFee($event)'

app/views/admin/order_cycles/_exchange_form.html.haml
%tr{ ng: { class: "'#{type} #{type}-{{ exchange.enterprise_id }}'" } }
  %td{:class => "#{type}_name"} {{ enterprises[exchange.enterprise_id].name }}
  %td.products.panel-toggle.text-center{ name: "products" }
    {{ exchangeSelectedVariants(exchange) }} /
    - if type == 'supplier'
      {{ enterpriseTotalVariants(enterprises[exchange.enterprise_id]) }}
    - else
      {{ (incomingExchangeVariantsFor(exchange.enterprise_id)).length }}
    = t('.selected')
  - if type == 'supplier'
    %td.receival-details
      = text_field_tag 'order_cycle_incoming_exchange_{{ $index }}_receival_instructions', '', 'id' => 'order_cycle_incoming_exchange_{{ $index }}_receival_instructions', 'placeholder' => t('.receival_instructions_placeholder'), 'ng-model' => 'exchange.receival_instructions'
  - if type == 'distributor'
    %td.tags.panel-toggle.text-center{ name: "tags", ng: { if: 'enterprises[exchange.enterprise_id].managed || order_cycle.viewing_as_coordinator' } }
      {{ exchange.tags.length }}
    %td.collection-details
      = text_field_tag 'order_cycle_outgoing_exchange_{{ $index }}_pickup_time', '', 'id' => 'order_cycle_outgoing_exchange_{{ $index }}_pickup_time', 'required' => 'required', 'placeholder' => t('.pickup_time_placeholder'), 'ng-model' => 'exchange.pickup_time', 'ng-disabled' => '!enterprises[exchange.enterprise_id].managed && !order_cycle.viewing_as_coordinator', 'maxlength' => 35
      %span.icon-question-sign{'ofn-with-tip' => t('.pickup_time_tip')}
      %br/
      = text_field_tag 'order_cycle_outgoing_exchange_{{ $index }}_pickup_instructions', '', 'id' => 'order_cycle_outgoing_exchange_{{ $index }}_pickup_instructions', 'placeholder' => t('.pickup_instructions_placeholder'), 'ng-model' => 'exchange.pickup_instructions', 'ng-disabled' => '!enterprises[exchange.enterprise_id].managed && !order_cycle.viewing_as_coordinator'
      %span.icon-question-sign{'ofn-with-tip' => t('.pickup_instructions_tip')}
  %td.fees
    %ol{ ng: { show: 'enterprises[exchange.enterprise_id].managed || order_cycle.viewing_as_coordinator' } }
      %li{'ng-repeat' => 'enterprise_fee in exchange.enterprise_fees'}
        = select_tag 'order_cycle_{{ exchangeDirection(exchange) }}_exchange_{{ $parent.$index }}_enterprise_fees_{{ $index }}_enterprise_id', nil, {'id' => 'order_cycle_{{ exchangeDirection(exchange) }}_exchange_{{ $parent.$index }}_enterprise_fees_{{ $index }}_enterprise_id', 'ng-model' => 'enterprise_fee.enterprise_id', 'ng-options' => 'enterprise.id as enterprise.name for enterprise in enterprisesWithFees()'}

        = select_tag 'order_cycle_{{ exchangeDirection(exchange) }}_exchange_{{ $parent.$index }}_enterprise_fees_{{ $index }}_enterprise_fee_id', nil, {'id' => 'order_cycle_{{ exchangeDirection(exchange) }}_exchange_{{ $parent.$index }}_enterprise_fees_{{ $index }}_enterprise_fee_id', 'ng-model' => 'enterprise_fee.id', 'ng-options' => 'enterprise_fee.id as enterprise_fee.name for enterprise_fee in enterpriseFeesForEnterprise(enterprise_fee.enterprise_id)'}

        = link_to 'Remove', '#', {'id' => 'order_cycle_{{ exchangeDirection(exchange) }}_exchange_{{ $parent.$index }}_enterprise_fees_{{ $index }}_remove', 'ng-click' => 'removeExchangeFee($event, exchange, $index)'}

    = f.submit t('.add_fee'), 'ng-click' => 'addExchangeFee($event, exchange)', 'ng-hide' => '!enterprises[exchange.enterprise_id].managed && !order_cycle.viewing_as_coordinator'
  %td.actions
    %a{'ng-click' => 'removeExchange($event, exchange)', :class => "icon-trash no-text remove-exchange"}

- if type == 'supplier'
  %tr.panel-row{ object: "exchange",
    panels: "{products: 'exchange_supplied_products'}",
    locals: "$index,order_cycle,exchange,enterprises,setExchangeVariants,suppliedVariants,removeDistributionOfVariant",
    colspan: 4 }
- if type == 'distributor'
  %tr.panel-row{ object: "exchange",
    panels: "{products: 'exchange_distributed_products', tags: 'exchange_tags'}",
    locals: "$index,order_cycle,exchange,supplied_products,setExchangeVariants,incomingExchangeVariantsFor,productSuppliedToOrderCycle,variantSuppliedToOrderCycle",
    colspan: 5 }

app/views/admin/order_cycles/_filters.html.haml
.filters.sixteen.columns.alpha.omega
  .filter.four.columns.alpha
    %label{ :for => 'query' }=t('admin.quick_search')
    %br
    %input.fullwidth{ :type => "text", :id => 'query', ng: { model: 'query' }, placeholder: t(".search_by_order_cycle_name") }
  .filter_select.four.columns
    %label{ :for => 'involving_filter' }=t('.involving')
    %br
    %input.ofn-select2.fullwidth{ id: 'involving_filter', type: 'number', blank: "{id: 0, name: '#{j t(".any_enterprise")}'}", data: 'enterprises', ng: { model: 'involvingFilter' } }
  - if subscriptions_enabled?
    .filter_select.four.columns
      %label{ :for => 'schedule_filter' }=t('admin.order_cycles.index.schedule')
      %br
      %input.ofn-select2.fullwidth{ id: 'schedule_filter', type: 'number', blank: "{id: 0, name: '#{j t(".any_schedule")}'}", data: 'schedules', ng: { model: 'scheduleFilter' } }
    .two.columns &nbsp;
  - else
    .six.columns &nbsp;
  .filter_clear.two.columns.omega
    %label{ :for => 'clear_all_filters' }
    %br
    %input.red.fullwidth{ :type => 'button', :id => 'clear_all_filters', :value => "#{t('admin.clear_all')}", ng: { click: "resetSelectFilters()" } }

app/views/admin/order_cycles/_header.html.haml
%colgroup
  %col{ ng: { show: 'columns.name.visible' } }
  %col{ ng: { show: 'columns.schedules.visible' } }
  %col{ ng: { show: 'columns.open.visible' }, style: 'width: 20%;' }
  %col{ ng: { show: 'columns.close.visible' }, style: 'width: 20%;' }
  - unless simple_index
    %col{ ng: { show: 'columns.producers.visible' } }
    %col{ ng: { show: 'columns.coordinator.visible' } }
    %col{ ng: { show: 'columns.shops.visible' } }
  %col{ ng: { show: 'columns.products.visible' } }
  %col{ style: 'width: 5%;' }
  %col{ style: 'width: 5%;' }
  %col{ style: 'width: 5%;' }

%thead
  %tr
    %th{ ng: { show: 'columns.name.visible' } }
      =t :name
    %th{ ng: { show: 'columns.schedules.visible' } }
      =t('admin.order_cycles.index.schedules')
    %th{ ng: { show: 'columns.open.visible' } }
      =t :open
    %th{ ng: { show: 'columns.close.visible' } }
      =t :close
    - unless simple_index
      %th{ ng: { show: 'columns.producers.visible' } }
        =t :label_producers
      %th{ ng: { show: 'columns.coordinator.visible' } }
        =t :coordinator
      %th{ ng: { show: 'columns.shops.visible' } }
        =t :label_shops
    %th{ ng: { show: 'columns.products.visible' } }
      =t :products
    %th.actions
    %th.actions
    %th.actions

app/views/admin/order_cycles/_loading_flash.html.haml
%div.sixteen.columns.alpha.omega#loading{ ng: { cloak: true, if: 'RequestMonitor.loading' } }
  %img.spinner{ src: "/assets/spinning-circles.svg" }
  %h1{ ng: { hide: 'orderCycles.length > 0' } } LOADING ORDER CYCLES
  %h1{ ng: { show: 'orderCycles.length > 0' } } LOADING...

app/views/admin/order_cycles/_name_and_timing_form.html.haml
.row
  .alpha.two.columns
    = f.label :name, t('.name')
  .six.columns.omega
    - if viewing_as_coordinator_of?(@order_cycle)
      = f.text_field :name, 'ng-model' => 'order_cycle.name', 'required' => true, 'ng-disabled' => '!loaded()'
    - else
      {{ order_cycle.name }}
  .two.columns
    = f.label :orders_open_at, t('.orders_open')
  .omega.six.columns
    - if viewing_as_coordinator_of?(@order_cycle)
      = f.text_field :orders_open_at, 'datetimepicker' => 'order_cycle.orders_open_at', 'ng-model' => 'order_cycle.orders_open_at', 'ng-disabled' => '!loaded()', 'change-warning' => 'order_cycle'
    - else
      {{ order_cycle.orders_open_at }}

.row
  .alpha.two.columns
    = f.label :coordinator, t('.coordinator')
  .six.columns.omega
    = @order_cycle.coordinator.name
  .two.columns
    = f.label :orders_close, t('.orders_close')
  .six.columns.omega
    - if viewing_as_coordinator_of?(@order_cycle)
      = f.text_field :orders_close_at, 'datetimepicker' => 'order_cycle.orders_close_at', 'ng-model' => 'order_cycle.orders_close_at', 'ng-disabled' => '!loaded()', 'change-warning' => 'order_cycle'
    - else
      {{ order_cycle.orders_close_at }}


- if subscriptions_enabled?
  .row
    .two.columns.alpha
      = f.label :schedule_ids, t('admin.order_cycles.index.schedules')
    .twelve.columns
      - if viewing_as_coordinator_of?(@order_cycle)
        %input.fullwidth.ofn-select2#schedule_ids{ name: 'order_cycle[schedule_ids]',
          data: 'schedules',
          multiple: 'true',
          placeholder: t('admin.please_select'),
          filter: '{viewing_as_coordinator: true}',
          ng: { model: 'order_cycle.schedule_ids' } }
      - else
        %schedule-list{ 'order-cycle' => 'order_cycle' }
    .two.columns.omega
      &nbsp;